picasso: Revert: "add firmware mount points"
Looks good but ends up in the following error:

[  0% 2/20730] build out/target/product/picasso/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin
FAILED: out/target/product/picasso/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin
/bin/bash -c "(out/host/linux-x86/bin/checkfc out/target/product/picasso/obj/ETC/sepolicy_intermediates/sepolicy out/target/product/picasso/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp ) && (out/host/linux-x86/bin/sefcontext_compile -o out/target/product/picasso/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin out/target/product/picasso/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp )"
out/target/product/picasso/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp:  line 676 has invalid file type u:object_r:persist_file:s0#
out/target/product/picasso/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp:  line 676 has invalid file type u:object_r:persist_file:s0#
Error: could not load context file from out/target/product/picasso/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp

Reverting this shouldn't cause any other sepolicy error.